### ISSUE TITLE
Curious...

### ISSUE THREAD

**Issue by allday5850** [Young-Lord/replaceCursor#1]
Could this be used to replace other resources other than the present ones it's intended for?
Like for example if I wanted to replace my "fingerprint" icon on lock screen? Or some other resources ? If I find the correct resource I.D. of course. 
If it comes down to--"only one way to find out" then that's fine I'm willing to experiment. But before I bootloop I'm jw if you had any input

**Comment by Young-Lord** [comment]
Possibly yes.
In my case, wrong replace only cause icon not showing, but not System / SystemUI die. Even if it happens, booting into safe mode and uninstall the module can recover.

**Comment by allday5850** [comment]
Music to my ears. Thank you
